job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, this project is amended by ooje its a small Maven project hosted on github")
    sh('''
    git config user.name 'ooje2022'
    git config user.email 'johnson.o.ojeniyi@gmail.com'
    ''')

    scm {
        git("https://github.com/ooje2022/DO-jenkins-maven-sample.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}