pipeline {
    agent any
    tools {
    	maven 'local-maven'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                   echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
    stage('Deploy in Staging Area'){
	    	build job: 'ashul-deploy-app-staging-env'
	    }
        }
    }
}
